"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[character]
success_symbol = '[❯](bold red)[❯](bold green)[❯](bold blue)'
error_symbol = '[❯❯❯](bold red)'

[package]
disabled = true

[git_branch]
format = '[$symbol$branch (:$remote_branch)]($style)'

[git_status]
untracked = "[push](bold red)"
